### PR TITLE
persistent avatars, checkmark icon, dynamic list, ios bugs

### LINKED ISSUE #10: Create functionality for answered questions
#### Answered questions should be shown as:
image
#### Questions that hasn't been answered yet should be shown as:
image

### LINKED ISSUE #35: Add button functionality for profile list item
The user should be able to enter a specific thread from the profile by clicking an item.

### LINKED ISSUE #37: input field is not visible on iphone

### LINKED ISSUE #40: add checkmark icon to checkmark button

### LINKED ISSUE #42: make avatars persistent

### PR DESCRIPTION
**Pull request by Monjola**
This PR fixes  #35 #37  #40  #42 

 - currentAvatar is now a cookie instead of a state, and lifted from Profile.tsx to Tabbar.tsx
- an  tag with the checkmark icon is added inside of all checkmark <button>'s
- Now, when you add a new question and send a message, it is added to the profile question list, and when you click the items in the question list the correct chat history is loaded, however the correct socket connection is not established see issue #36 
- some ios bugs are fixed, tabbar on small devices is same size as large devices and input bar bottom margin is added to correct for previous error where input bar was not visible. However in standalone mode input bar is very high up for now, could probably be fixed with another conditional css setting.

### CODE REVIEW

File: src/components/ChatApp/ChatApp.tsx [hunk 1]
```diff
@@ -47,11 +47,22 @@ export default function ChatApp(props) {
 
   function onSubjectSelect(subject: api.Subject) {
     let firstVisit = props.allChats === undefined;
-    console.log('onSubjectSelecKörs');
     if (firstVisit) {
       props.setAllChats(
         `{ "allThreadIds" : [], "allChannelIds" : [], "text" : [], "imageURL" : [], "checkmark" : [${false}]}`
       );
+      // new
```
Comment (iRobsc) [inline src/components/ChatApp/ChatApp.tsx]: What are the new comment tags for?

File: src/components/Popup/Popup.tsx [hunk 2]
```diff
@@ -1,5 +1,4 @@
 import React, { useState } from 'react';
-import ReCAPTCHA from 'react-google-recaptcha';
```
Comment (iRobsc) [inline src/components/Popup/Popup.tsx:2]: Is ReCAPTCHA only removed for testing purposes or will it be removed for the future of the project? Since this change will remain in the pull request to the main repository when that happens too.

File: src/components/Popup/Popup.tsx [hunk 3]
```diff
@@ -51,19 +45,17 @@ export function Popup(props: PopupProps) {
             />
             <span>I agree to the terms of service</span>
           </div>
-          <ReCAPTCHA
+          {/* <ReCAPTCHA
```
Comment (iRobsc) [inline src/components/Popup/Popup.tsx]: Commented code.

File: src/components/Profile/Item.tsx [hunk 4]
```diff
@@ -2,16 +2,40 @@ import React from 'react';
...
   return (
-    <div className="profile-item" onClick={() => props.goToChat(0)}>
+    <div className="profile-item" onClick={() => props.goToChat(props.index)}>
       {props.checkmark ? (
-        <div className="profile-item-checkmark" />
+        <div className="profile-item-checkmark">
+          <img
+            src="icons/check-mark-3-512.png"
+            alt="checkmark"
+            style={{
```
Comment (iRobsc) [inline src/components/Profile/Item.tsx]: Inline styling for multiple rows should probably have its own class in the css. Otherwise it creates inconsistency within the project.

File: src/components/Tabbar/Tabbar.tsx [hunk 5]
```diff
@@ -18,20 +18,30 @@ export default function Tabbar() {
...
   const setAllChatsChild = (allChatsChild) => setAllChats(allChatsChild);
-
+  const [allChatsArray, setAllChatsArray] = useCookie('allChatsArray');
+  const setAllChatsArrayChild = (allChatsArrayChild) =>
+    setAllChatsArray(allChatsArrayChild);
+  const [currentAvatar, setCurrentAvatar] = useCookie('currentAvatar');
   const goToChat = (itemIndex) => {
-    setThreadId(allChats.allThreadIds[itemIndex]);
-    setChannelId(allChats.allChannelIds[itemIndex]);
+    console.log(itemIndex);
```
Comment (iRobsc) [inline src/components/Tabbar/Tabbar.tsx]: Test log here.

File: src/index.sass [hunk 6]
```diff
@@ -579,17 +582,18 @@ button
     #subjects-container
         button
             width: 48%
-    #tab-bar
-        button 
-            img
-                width: 30px
+    // #tab-bar
```
Comment (iRobsc) [inline src/index.sass]: Commented code line 585 to 591.

**Review by iRobsc — CHANGES_REQUESTED** [review]
Requested changes below.

File: src/components/Popup/Popup.tsx (hunk 2 above)
Comment (Monjola) [reply src/components/Popup/Popup.tsx:2]: This will have to be removed for presentation but be reintroduced later

File: src/components/Tabbar/Tabbar.tsx (hunk 5 above)
Comment (Monjola) [reply src/components/Tabbar/Tabbar.tsx]: removed.

File: src/index.sass (hunk 6 above)
Comment (Monjola) [reply src/index.sass]: removed.

File: src/components/Popup/Popup.tsx (hunk 3 above)
Comment (Monjola) [reply src/components/Popup/Popup.tsx]: removed.

File: src/components/Profile/Item.tsx (hunk 4 above)
Comment (Monjola) [reply src/components/Profile/Item.tsx]: fixed.

**Review by iRobsc — APPROVED** [review]
LGTM
